// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqeMyr6cRjhydbn7OwjaWS7kFcJjE6e5Y',
    appId: '1:317796345447:web:6f5ad8db419dd3b43056c2',
    messagingSenderId: '317796345447',
    projectId: 'chatpalm-612da',
    authDomain: 'chatpalm-612da.firebaseapp.com',
    storageBucket: 'chatpalm-612da.appspot.com',
    measurementId: 'G-ZV69R7QREY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy7SeATK_g5i3yi6-y8E9PutfugOw6Tdc',
    appId: '1:317796345447:android:ffcd4e2f9f6c899e3056c2',
    messagingSenderId: '317796345447',
    projectId: 'chatpalm-612da',
    storageBucket: 'chatpalm-612da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_gOOffTaX3z5DmsCVjfdQgV7xT5moaF4',
    appId: '1:317796345447:ios:b136a6176b197a6c3056c2',
    messagingSenderId: '317796345447',
    projectId: 'chatpalm-612da',
    storageBucket: 'chatpalm-612da.appspot.com',
    iosClientId: '317796345447-rba76hi01d27glapnkonlqc3bdu12edf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatpalmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_gOOffTaX3z5DmsCVjfdQgV7xT5moaF4',
    appId: '1:317796345447:ios:193f6383e9d595cc3056c2',
    messagingSenderId: '317796345447',
    projectId: 'chatpalm-612da',
    storageBucket: 'chatpalm-612da.appspot.com',
    iosClientId: '317796345447-8j55g66ksavc5gqkpc3145k98pfef0e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatpalmApp.RunnerTests',
  );
}
